/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class fr_planquart_jni_JNIActivity */

#ifndef _Included_fr_planquart_jni_JNIActivity
#define _Included_fr_planquart_jni_JNIActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     fr_planquart_jni_JNIActivity
 * Method:    getJNIText
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_fr_planquart_jni_JNIActivity_getJNIText
  (JNIEnv *, jobject);

/*
 * Class:     fr_planquart_jni_JNIActivity
 * Method:    JNIAdd
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_fr_planquart_jni_JNIActivity_JNIAdd
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     fr_planquart_jni_JNIActivity
 * Method:    JNIAdd
 * Signature: ()I
 */
JNIEXPORT jobject JNICALL Java_fr_planquart_jni_JNIActivity_getWindowSize
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
